language: objective-c
osx_image: xcode8.2
cache:
  directories:
  - Carthage
install:
  - brew update
  - brew outdated carthage || brew upgrade carthage
  - carthage bootstrap --no-use-binaries --platform $PLATFORM --cache-builds
before_script:
  - export LANG=en_US.UTF-8
script:
  - xcodebuild $ACTION -project OSRMTextInstructions.xcodeproj -scheme "$SCHEME" -destination "$DESTINATION" ONLY_ACTIVE_ARCH=NO
env:
  - PLATFORM=iOS SCHEME='OSRMTextInstructions iOS' ACTION=test DESTINATION='platform=iOS Simulator,name=iPhone 7,OS=10.1' ONLY_ACTIVE_ARCH=NO
  - PLATFORM=macOS SCHEME='OSRMTextInstructions macOS' ACTION=test DESTINATION='platform=OS X'
  - PLATFORM=tvOS SCHEME='OSRMTextInstructions tvOS' ACTION=test DESTINATION='platform=tvOS Simulator,name=Apple TV 1080p,OS=10.1'
  - PLATFORM=watchOS SCHEME='OSRMTextInstructions watchOS' ACTION=build DESTINATION='platform=watchOS Simulator,name=Apple Watch Series 2 - 42mm,OS=3.1'
